### ISSUE TITLE
Review Kresus v0.7

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/blog.benj.me#2]
https://blog.benj.me/2016/01/18/kresus-version-0-7-0
https://github.com/bnjbvr/blog.benj.me/blob/sources/content/blog/2016-01-18_kresus-version-070.md
r? @adngdb

**Comment by adngdb** [comment]
https://github.com/bnjbvr/blog.benj.me/pull/3

**Comment by bnjbvr** [comment]
:+1:
